import Login from "@/components/Auth/Login";
import Head from "next/head";
import Link from "next/link";
import React from "react";

const LoginPage = () => {
	return (
		<>
			<Head>
				<title>Capital Transaction | register</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="min-h-screen flex flex-col sm:flex-row overflow-y-auto">
				<div className="min-h-96 md:w-7/12 flex flex-col py-15 px-11 md:py-20 md:px-16">
					<h1 className="font-bold text-3xl md:text-5xl py-5 text-theamP">
						Capital Transactions
					</h1>
					<div className="flex-1 flex flex-col justify-center">
						<div className="space-y-6 px-1 py-5">
							<h2 className="text-3xl md:text-6xl">
								Welcome Back !
							</h2>
							<p className="md:w-8/12">
								Lorem ipsum dolor sit amet, consectetur
								adipiscing elit, sed do eiusmod tempor
								incididunt ut labore et dolore magna aliqua. Ut
								enim ad minim veniam, quis nostrud exercitation
								ullamco laboris nisi ut aliquip ex ea commodo
								consequat.
							</p>
							<Link
								href="/"
								className="bg-theamP  w-1/3 sm:w-52 py-2 block text-white rounded-md text-center"
							>
								Register
							</Link>
						</div>
					</div>
				</div>
				<div className="flex flex-1 flex-col justify-center items-center bg-theamP px-10">
					<Login />
				</div>
			</main>
		</>
	);
};

export default LoginPage;
